---
- name: reload opendkim
  service: 
      name: "opendkim"
      state: reloaded

- name: restart opendkim
  service: 
    name: "opendkim"
    state: "restarted"

- name: reload postfix
  service: 
    name: "postfix"
    state: "restarted"

